package ChildCareTech.services;

import ChildCareTech.Client;
import ChildCareTech.controller.MainWindowControllerInterface;
import javafx.event.EventHandler;
import javafx.fxml.FXMLLoader;
import javafx.fxml.LoadException;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;

import java.io.IOException;

/**
 * This class provides a window management service for the main application's stages.
 */

public class MainWindowService {
    private Stage stage;
    private FXMLLoader loader;
    private String userName;

    /**
     * Creates a MainWindowService instance based on a new stage created internally and sets
     * the window for calling the logoutAttempt method and log out from server session.
     */
    public MainWindowService() {
        stage = new Stage();
        stage.setOnCloseRequest(new EventHandler<WindowEvent>() {
            @Override
            public void handle(WindowEvent event) {
                Client.getSessionService().logoutAttempt();
            }
        });
    }

    /**
     * Creates a MainWindowService instance based on the stage passed as parameter.
     * <p>
     * Should be used for the application's most foreground windows.
     * @param stage the stage that will be used to display the window.
     *              Should be the primaryStage generated by the start of the Application instance.
     */
    public MainWindowService(Stage stage) {
        this.stage = stage;
    }

    /**
     * Closes the stage.
     */
    public void close() {
        stage.close();
    }
    public void show() {
        stage.show();
    }
    public void hide() {
        stage.hide();
    }

    /**
     * Sets the stage's title.
     * @param string the title.
     */
    public void setTitle(String string) { stage.setTitle(string); }
    public void setResizable(boolean bool) { stage.setResizable(bool); }
    public double getHeight() {
        return stage.getHeight();
    }
    public double getWidth() {
        return stage.getWidth();
    }
    private void setScene(Scene scene) {
        stage.setScene(scene);
    }

    /**
     * Sets a method that will be called by the closing of the stage.
     * @param eventEventHandler the eventHandler that contains the method.
     */
    public void setOnCloseAction(EventHandler<WindowEvent> eventEventHandler) {
        stage.setOnCloseRequest(eventEventHandler);
    }
    public void setUserName(String userName) { this.userName = userName; }
    public String getUserName() { return userName; }
    public Stage getStage() {
        return this.stage;
    }

    /**
     * Loads the login window from the ResourcesPaths' relative fxml and css files' addresses.
     * @throws IOException in case the fxml's or css' paths are incorrect.
     */
    public void loadLoginWindow() throws IOException{
        loadWindow(ResourcesPaths.getLoginFXMLPath(), ResourcesPaths.getLoginCSSPath());
        ((MainWindowControllerInterface)loader.getController()).setMainWindowService(this);
    }

    /**
     * Loads the main application's window from the ResourcesPaths' relative fxml and css files' addresses.
     * @throws IOException in case the fxml's or css' paths are incorrect.
     */
    public void loadMainWindow() throws IOException{
        loadWindow(ResourcesPaths.getMainWindowFXMLPath(), ResourcesPaths.getMainWindowCSSPath());
        ((MainWindowControllerInterface)loader.getController()).setMainWindowService(this);
    }
    /**
     * Loads the day generation window from the ResourcesPaths' relative fxml and css files' addresses.
     * @throws IOException in case the fxml's or css' paths are incorrect.
     */
    public void loadDayGenerationWindow() throws IOException{
        loadWindow(ResourcesPaths.getDayGenerationFXMLPath(), ResourcesPaths.getDayGenerationCSSPath());
        ((MainWindowControllerInterface)loader.getController()).setMainWindowService(this);
    }

    /**
     * Creates a new scene from the FXML' path parameter file and adds to it the style from the CSS' path parameter,
     * suddenly sets it to the stage.
     * @param fxmlPath the path for the FXML file
     * @param cssPath the path for the CSS file
     * @throws IOException in case the fxml's or css' paths are incorrect.
     */
    private void loadWindow(String fxmlPath, String cssPath) throws IOException {
        loader = new FXMLLoader(AccessorWindowService.class.getResource(fxmlPath));
        try {
            Scene scene = new Scene(loader.load());
            scene.getStylesheets().add(cssPath);
            stage.setScene(scene);
        } catch(LoadException ex) {
            System.err.println("error loading fxml file: "+fxmlPath+", "+cssPath);
            ex.printStackTrace();
        }
        stage.show();
    }
}
